---
title: "Preprocessing and clustering in scRNA"
output: html_notebook
---

```{r}
# Load packages, etc.
library(Seurat)
library(tidyverse)
library(SeuratData)
library(patchwork)
library(ggplot2)
DATA_PATH = "~/Desktop/b545_g4_project/data/RNA/"
source("../scripts/io.R")
sessionInfo()
```


```{r}
# Load data into one, merged Seurat object

# Load DMSO data and filter out doublets ()
counts_DMSO <- load_scRNA(paste0(DATA_PATH,"/DMSO/"))
DMSO_RNA <- CreateSeuratObject(counts = counts_DMSO, assay = 'RNA', project = 'DMSO_1')
DMSO_RNA$type = 'DMSO'

# Load ResA data
counts_ResA <- load_scRNA(paste0(DATA_PATH,"/ResA/"))
ResA_RNA <- CreateSeuratObject(counts = counts_ResA, assay = 'RNA', project = "ResA_1'")
ResA_RNA$type = 'ResA'

# Combine datasets
combined_RNA <- merge(x=DMSO_RNA, y=ResA_RNA, add.cell.ids=c('DMSO','ResA'))

# Delete individual datasets
rm(DMSO_RNA, ResA_RNA)
gc()
combined_RNA
```


```{r}
# Calculate and visualize QC metrics
combined_RNA[["percent.mt"]] <- PercentageFeatureSet(combined_RNA, pattern = "^MT-")
VlnPlot(combined_RNA, features=c('nCount_RNA','nFeature_RNA',"percent.mt"), ncol=3, group.by='type')
FeatureScatter(combined_RNA, "nCount_RNA", "nFeature_RNA", group.by = "orig.ident", pt.size = 0.5)
```


```{r}
# Filter out cells with low # genes expressed (< 2000).
# Also exclude genes expressed in less than 5 cells
# Since there are no cells expressing mitochondrial genes, I didn't bother to filter those out
selected_cells <- WhichCells(combined_RNA, expression = nFeature_RNA > 2000)
selected_genes <- rownames(combined_RNA)[Matrix::rowSums(combined_RNA) > 4]

data.filt <- subset(combined_RNA, features = selected_genes, cells = selected_cells)
data.filt # We kept 18,442 genes and 6567 cells.

# Re-visualize QC metrics with filtered data
VlnPlot(data.filt, features=c('nCount_RNA','nFeature_RNA',"percent.mt"), ncol=3, group.by='type')
```


```{r}
# Doublet prediction with DoubletFinder
# remotes::install_github('chris-mcginnis-ucsf/DoubletFinder')
library(DoubletFinder)

# It requires that I run clustering before detecting doublets
data.filt = FindVariableFeatures(data.filt, verbose = F)
data.filt = ScaleData(data.filt, vars.to.regress = c("nFeature_RNA", 'nCount_RNA'),
    verbose = F)
data.filt = RunPCA(data.filt, verbose = F, npcs = 20)
data.filt = RunUMAP(data.filt, dims = 1:10, verbose = F)

nExp <- round(ncol(data.filt) * 0.06)  # expect ~6% doublets if  ~8k cells were loaded per sample
data.filt <- doubletFinder_v3(data.filt, pN = 0.25, pK = 0.09, nExp = nExp, PCs = 1:10, sct=T)

# Visualize read counts based on doublet prediction
DF.name = colnames(data.filt@meta.data)[grepl("DF.classification", colnames(data.filt@meta.data))]
VlnPlot(data.filt, features = "nFeature_RNA", group.by = DF.name, pt.size = 0.1)

# Remove doublets
data.filt = data.filt[, data.filt@meta.data[, DF.name] == "Singlet"]
dim(data.filt)
```


```{r}
# Replot
```


```{r}
# Save data in notebooks folder
saveRDS(data.filt, "~/Desktop/b545_g4_project/notebooks/seurat_RNA_qc.rds")
```

```{r}
# To load in data: 
data.filt <- readRDS("~/Desktop/b545_g4_project/notebooks/seurat_RNA_qc.rds")
```

```{r}
# Plot UMAP on unintegrated data
data.filt <- RunPCA(data.filt, npcs=30, verbose=FALSE)
data.filt <- RunUMAP(data.filt, reduction='pca', dims=1:30)
DimPlot(data.filt, group.by='type') + labs(title='no integration')
```

```{r}
# Data integration with fastMNN

# First, normalize data and identify variable features
data.filt <- NormalizeData(data.filt)
data.filt <- FindVariableFeatures(data.filt)

# Run fastMNN
data.filt <- RunFastMNN(object.list=SplitObject(data.filt, split.by='orig.ident'))

# UMAP to visualize
data.filt <- RunUMAP(data.filt, reduction='mnn', dims=1:30)
DimPlot(data.filt, group.by='orig.ident')
```

```{r}
# Data integration with Seurat

# First, split the dataset into a list of 2 Seurat objects (DMSO and LNCaP)
data.list <- SplitObject(data.filt, split.by='orig.ident')

# Normalize and identify variable genes for each dataset separately
data.list <- lapply(X=data.list, FUN=function(x){
  x <- NormalizeData(x)
  x <- FindVariableFeatures(x, selection.method='vst', nfeatures=2000)
})

# Select features that are variable across datasets for integration
features <- SelectIntegrationFeatures(object.list=data.list)

# Perform integration
anchors <- FindIntegrationAnchors(object.list=data.list)

# Create integrated dataset
data.integrated <- IntegrateData(anchorset=anchors)

# UMAP for Seurat integration
DefaultAssay(data.integrated) <- "integrated"
data.integrated <- ScaleData(data.integrated, verbose=FALSE)
data.integrated <- RunPCA(data.integrated, npcs=30, verbose=FALSE)
data.integrated <- RunUMAP(data.integrated, reduction='pca', dims=1:30)
DimPlot(data.integrated, reduction='umap', group.by='type')
```
```{r}
# Data integration with harmony
library(harmony)
data.filt <- NormalizeData(data.filt) %>% FindVariableFeatures() %>% ScaleData() %>% RunPCA(verbose=FALSE)
data.filt <- RunHarmony(data.filt, group.by.vars='orig.ident')
data.filt <- RunUMAP(data.filt, reduction='harmony', dims=1:30)
DimPlot(data.filt, group.by='type')
```


### Possibly useful commands for preprocessing/clustering.

Use these if they are helpful. However, all code used by team members is above.
```{r}
# These are commands in the original .rmd file that I didn't use, so I left them here just in case.

# scrublet <- read.table("raw_data/10x_scrna/pbmc10k_v3/matrix_doublets.tsv", sep = "\t", col.names = c('observed', 'simulated'))
# rownames(scrublet) <- colnames(counts)
# rna <- AddMetaData(rna, metadata = scrublet)
# rna <- RenameCells(rna, add.cell.id = 'rna')
# mito.features <- grep(pattern = "^MT-", x = rownames(x = rna), value = TRUE)
# percent.mito <- Matrix::colSums(x = GetAssayData(object = rna, slot = 'counts')[mito.features, ]) / Matrix::colSums(x = GetAssayData(object = rna, slot = 'counts'))
# rna$percent.mito <- percent.mito
# 
# # QC
# rna <- subset(x = rna, subset = nCount_RNA > 2000 & nCount_RNA < 20000 & percent.mito < 0.2)
# 
# # preprocessing
# rna <- NormalizeData(rna)
# rna <- FindVariableFeatures(rna, nfeatures = 3000)
# rna <- ScaleData(rna)
# rna <- RunPCA(rna, npcs = 100)
# rna <- RunTSNE(rna, dims = 1:30)
# rna <- FindNeighbors(rna, dims = 1:30)
# rna <- FindClusters(rna, resolution = 0.4, algorithm = 3)
# rna <- RunUMAP(rna, graph = 'RNA_nn', metric = 'euclidean')

# new.cluster.ids <- c(
#   "CD14+ Monocytes",
#   'CD4 Memory',
#   'CD4 Naive',
#   'pre-B cell',
#   'Double negative T cell',
#   'NK cell',
#   'B cell progenitor',
#   'CD8 effector',
#   'CD8 Naive',
#   'CD16+ Monocytes',
#   'Dendritic cell', 
#   'pDC',
#   'Platelet'
# )
# 
# names(x = new.cluster.ids) <- levels(x = rna)
# rna <- RenameIdents(object = rna, new.cluster.ids)
# rna$celltype <- Idents(rna)
# nk.cells <- subset(rna, subset = celltype == 'NK cell')
# gzmk <- GetAssayData(nk.cells, assay = 'RNA', slot = 'data')['GZMK', ]
# nk.cells$bright <- ifelse(gzmk > 1, 'NK bright', 'NK dim')
# ctypes <- as.vector(rna$celltype)
# names(ctypes) <- names(rna$celltype)
# ctypes[Cells(nk.cells)] <- nk.cells$bright
# rna <- AddMetaData(rna, metadata = ctypes, col.name = 'celltype')
# saveRDS(rna, paste0(DATA_PATH,"LNCaP/rna.rds"))
```
```{r}
# clustering anlaysis
seurat_RNA_obj <- readRDS("seurat_RNA_qc.rds")
# clustering data
seurat_RNA_obj <- FindNeighbors(seurat_RNA_obj, dims= 1:10)
seurat_RNA_obj <- FindClusters(seurat_RNA_obj, resolution = 0.5)
#non-linear dimension reduction (UMAP)
seurat_RNA_obj <- RunUMAP(seurat_RNA_obj, dims = 1:10)
# Visualize the clusters
DimPlot(seurat_RNA_obj, reduction = "umap", label= TRUE)
# Find markers for each of the 10 clusters
cluster0.markers <- FindMarkers(seurat_RNA_obj, ident.1= 0, min.pct = 0.3)
cluster1.markers <- FindMarkers(seurat_RNA_obj, ident.1= 1, min.pct = 0.3)
cluster2.markers <- FindMarkers(seurat_RNA_obj, ident.1= 2, min.pct = 0.3)
cluster3.markers <- FindMarkers(seurat_RNA_obj, ident.1= 3, min.pct = 0.3)
cluster4.markers <- FindMarkers(seurat_RNA_obj, ident.1= 4, min.pct = 0.3)
cluster5.markers <- FindMarkers(seurat_RNA_obj, ident.1= 5, min.pct = 0.3)
cluster6.markers <- FindMarkers(seurat_RNA_obj, ident.1= 6, min.pct = 0.3)
cluster7.markers <- FindMarkers(seurat_RNA_obj, ident.1= 7, min.pct = 0.3)
cluster8.markers <- FindMarkers(seurat_RNA_obj, ident.1= 8, min.pct = 0.3)
cluster9.markers <- FindMarkers(seurat_RNA_obj, ident.1= 9, min.pct = 0.3)

# Convert ensemble ID to gene symbols
library("EnsDb.Hsapiens.v79")
ensemb0.genes <- c("ENSG00000106153", "ENSG00000169567", "ENSG00000065978", "ENSG00000104904", 
                   "ENSG00000124172", "ENSG00000163584", "ENSG00000221983", "ENSG00000127184", 
                   "ENSG00000140264", "ENSG00000174444")
geneIDs0 <- ensembldb::select(EnsDb.Hsapiens.v79, keys= ensemb0.genes, keytype = "GENEID", columns = c("SYMBOL","GENEID"))

ensemb1.genes <- c("ENSG00000198300", "ENSG00000142541", "ENSG00000130066", "ENSG00000134755", 
                   "ENSG00000143158", "ENSG00000086205", "ENSG00000166342", "ENSG00000184012", 
                   "ENSG00000171451", "ENSG00000167034")
geneIDs1 <- ensembldb::select(EnsDb.Hsapiens.v79, keys= ensemb1.genes, keytype = "GENEID", columns = c("SYMBOL","GENEID"))

ensemb2.genes <- c("ENSG00000128272", "ENSG00000187840", "ENSG00000173812", "ENSG00000135069", "ENSG00000130513", "ENSG00000168003", "ENSG00000125977", "ENSG00000151012", "ENSG00000106105", "ENSG00000092621")
geneIDs2 <- ensembldb::select(EnsDb.Hsapiens.v79, keys= ensemb2.genes, keytype = "GENEID", columns = c("SYMBOL","GENEID"))

ensemb3.genes <- c("ENSG00000132646", "ENSG00000112118", "ENSG00000065328", "ENSG00000143476", "ENSG00000094804", "ENSG00000131153", "ENSG00000104738", "ENSG00000092853", "ENSG00000012048", "ENSG00000189057")
geneIDs3 <- ensembldb::select(EnsDb.Hsapiens.v79, keys= ensemb3.genes, keytype = "GENEID", columns = c("SYMBOL","GENEID"))

ensemb4.genes <- c("ENSG00000070961", "ENSG00000143819", "ENSG00000161011", "ENSG00000143416", "ENSG00000189403", "ENSG00000198363", "ENSG00000187514", "ENSG00000197061", "ENSG00000117632", "ENSG00000131711")
geneIDs4 <- ensembldb::select(EnsDb.Hsapiens.v79, keys= ensemb4.genes, keytype = "GENEID", columns = c("SYMBOL","GENEID"))                              

ensemb5.genes <- c("ENSG00000072571", "ENSG00000164611", "ENSG00000134057", "ENSG00000117399", "ENSG00000100526","ENSG00000126787", "ENSG00000108106", "ENSG00000157456", "ENSG00000089685", "ENSG00000166851")
geneIDs5 <- ensembldb::select(EnsDb.Hsapiens.v79, keys= ensemb5.genes, keytype = "GENEID", columns = c("SYMBOL","GENEID"))

ensemb6.genes <- c("ENSG00000111666", "ENSG00000092841", "ENSG00000166165", "ENSG00000143416", "ENSG00000175130", "ENSG00000160213", "ENSG00000114784", "ENSG00000111716", "ENSG00000109971", "ENSG00000068985")
geneIDs6 <- ensembldb::select(EnsDb.Hsapiens.v79, keys= ensemb6.genes, keytype = "GENEID", columns = c("SYMBOL","GENEID"))

ensemb7.genes <- c("ENSG00000123485", "ENSG00000080986", "ENSG00000075218", "ENSG00000143228", "ENSG00000115163", "ENSG00000137812", "ENSG00000138180", "ENSG00000137807", "ENSG00000139734", "ENSG00000090889")
geneIDs7 <- ensembldb::select(EnsDb.Hsapiens.v79, keys= ensemb7.genes, keytype = "GENEID", columns = c("SYMBOL","GENEID"))

ensemb8.genes <- c("ENSG00000125144", "ENSG00000132872", "ENSG00000258162", "ENSG00000167332", "ENSG00000118263", "ENSG00000111913", "ENSG00000165272", "ENSG00000142515", "ENSG00000151715", "ENSG00000183960")
geneIDs8 <- ensembldb::select(EnsDb.Hsapiens.v79, keys= ensemb8.genes, keytype = "GENEID", columns = c("SYMBOL","GENEID"))

ensemb9.genes <- c("ENSG00000247095", "ENSG00000173511", "ENSG00000167751", "ENSG00000104419", "ENSG00000167749", "ENSG00000116014", "ENSG00000184012", "ENSG00000102144", "ENSG00000131016", "ENSG00000142515")
geneIDs9 <- ensembldb::select(EnsDb.Hsapiens.v79, keys= ensemb9.genes, keytype = "GENEID", columns = c("SYMBOL","GENEID"))

# Rename clusters based on cell type
library(scCustomize)                                
renamed_clusters_seurat_RNA_obj <- Rename_Clusters(seurat_object = seurat_RNA_obj, new_idents = c("Basal cells 38", "Neurons", "Fibroblasts", "Testis germ cells", "Myocytes", "Erythroid & its precursor cells", "Testicle germ cells", "Hepatocytes", "Basal cells 3","Epithelial cells"), meta_col_name = "annotated_cell_type")

```
